### ISSUE TITLE
Weird exception when using arrow.get on malformed string

### ISSUE THREAD

**Issue by Google-Autofuzz** [arrow-py/arrow#854]
I'm getting an exception from `re` when running the following script on the attached output:

```python
import arrow
import sys

with open(sys.argv[1]) as f:
    data = f.read()

fmtstr, payload = str(data[:24]), str(data[24:])
arrow.get(payload, fmtstr).humanize()
```

[clusterfuzz-testcase-minimized-fuzz_get-5739607865688064.txt](https://github.com/arrow-py/arrow/files/5283269/clusterfuzz-testcase-minimized-fuzz_get-5739607865688064.txt)

```python
$ cat clusterfuzz-testcase-minimized-fuzz_get-5739607865688064 
struct n[X+,N-M)MMXdMM]<(ven) 
$ python test.py clusterfuzz-testcase-minimized-fuzz_get-5739607865688064 
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    arrow.get(payload, fmtstr).humanize()
  File "/home/user/ven/lib/python3.8/site-packages/arrow/api.py", line 21, in get
    return _factory.get(*args, **kwargs)
  File "/home/user/ven/lib/python3.8/site-packages/arrow/factory.py", line 246, in get
    dt = parser.DateTimeParser(locale).parse(
  File "/home/user/ven/lib/python3.8/site-packages/arrow/parser.py", line 227, in parse
    fmt_tokens, fmt_pattern_re = self._generate_pattern_re(fmt)
  File "/home/user/ven/lib/python3.8/site-packages/arrow/parser.py", line 324, in _generate_pattern_re
    return tokens, re.compile(bounded_fmt_pattern, flags=re.IGNORECASE)
  File "/usr/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 962, in parse
    raise source.error("unbalanced parenthesis")
re.error: unbalanced parenthesis at position 85
$
```
I would be nice to catch it, and to raise an `arrow`-related exception instead.

## System Info

- 🖥 **OS name and version**: Linux x64 (Debian)
- 🐍 **Python version**: 3.8.5
- 🏹 **Arrow version**: 0.16.0

**Comment by jadchaar** [comment]
Thanks for reporting this. As part of a fix, we should probably do the following:

- [ ] Audit regular expression logic to ensure that we are escaping in all control paths (at least, whenever possible)
- [ ] Wrap `re`-related exceptions in an `ArrowParserError`
